server:
  port: 8080
  servlet:
    context-path: /car-project/api/v1

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/car-test-project
    username: car-user
    password: car-user-password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: true
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: info
    org.hibernate.SQL: info

